"use client";

import { useCallback, useEffect, useState } from "react";
import { motion } from "framer-motion";
import {
  Sparkles,
  Loader2,
  RefreshCw,
  AlertTriangle,
  UserCheck,
  ShieldAlert,
} from "lucide-react";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { PriorityBadge, CategoryBadge } from "@/components/dashboard/status-badge";
import {
  fetchAiTriage,
  runAiTriage,
  type AiTriageRun,
} from "@/lib/citizen-api";

function percent(p: number): string {
  return `${Math.round(p * 100)}%`;
}

export function AiAnalysisCard({ complaintId }: { complaintId: string }) {
  const [run, setRun] = useState<AiTriageRun | null>(null);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [reloadKey, setReloadKey] = useState(0);

  useEffect(() => {
    let cancelled = false;
    fetchAiTriage(complaintId)
      .then((r) => {
        if (!cancelled) {
          setRun(r);
          setError(null);
        }
      })
      .catch((e) => {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : "Could not load AI analysis.");
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [complaintId, reloadKey]);

  const analyze = useCallback(async () => {
    setRunning(true);
    setError(null);
    try {
      const resp = await runAiTriage(complaintId, "en");
      setReloadKey((k) => k + 1);
      if (resp.status === "FAILED") {
        setError(resp.error || "AI analysis failed. You can retry.");
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Failed to run AI analysis.";
      setError(msg);
    } finally {
      setRunning(false);
    }
  }, [complaintId]);

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-ai-500" /> AI Recommendation
          </CardTitle>
          <Badge variant="ai" className="w-fit">AI-generated · for review</Badge>
        </CardHeader>
        <CardContent className="space-y-3">
          <Skeleton className="h-4 w-40" />
          <Skeleton className="h-4 w-56" />
          <Skeleton className="h-4 w-48" />
        </CardContent>
      </Card>
    );
  }

  const result = run?.structured_result ?? null;
  const failed = run?.status === "FAILED";
  const inProgress = running || run?.status === "RUNNING";

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-ai-500" /> AI Recommendation
        </CardTitle>
        <CardDescription>
          Automated triage generated by the CivicAgent AI agent — advisory only,
          subject to human verification.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {inProgress && (
          <div className="flex items-center gap-3 rounded-lg border border-ai-100 bg-ai-50 p-3 text-sm text-ai-700">
            <Loader2 className="h-4 w-4 animate-spin" />
            Analyzing this complaint…
          </div>
        )}

        {error && (
          <div className="flex items-start gap-2 rounded-lg border border-danger-100 bg-danger-50 p-3 text-sm text-danger-700">
            <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {failed && !result && (
          <div className="flex items-center justify-between gap-3">
            <p className="text-sm text-slate-600">
              AI analysis failed. Your complaint is safe and you can retry.
            </p>
            <Button
              variant="outline"
              size="sm"
              onClick={analyze}
              disabled={running}
            >
              <RefreshCw className="mr-1.5 h-4 w-4" /> Retry
            </Button>
          </div>
        )}

        {!failed && !result && !inProgress && (
          <div className="flex flex-col items-center gap-3 py-2 text-center">
            <p className="text-sm text-slate-500">
              This complaint has not been analyzed yet.
            </p>
            <Button variant="default" size="sm" onClick={analyze} disabled={running}>
              <Sparkles className="mr-1.5 h-4 w-4" /> Analyze with AI
            </Button>
          </div>
        )}

        {result && (
          <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-4"
          >
            {result.human_review_required && (
              <div className="flex items-start gap-2 rounded-lg border border-warning-200 bg-warning-50 p-3 text-sm text-warning-800">
                <UserCheck className="mt-0.5 h-4 w-4 shrink-0" />
                <span>
                  Low-confidence result — this complaint was routed for manual
                  human review.
                </span>
              </div>
            )}

            <div className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <p className="text-xs text-slate-400">Category</p>
                <CategoryBadge value={result.category} />
              </div>
              <div>
                <p className="text-xs text-slate-400">Severity</p>
                <PriorityBadge value={result.severity} />
              </div>
              <div>
                <p className="text-xs text-slate-400">Urgency</p>
                <PriorityBadge value={result.urgency} />
              </div>
              <div>
                <p className="text-xs text-slate-400">Confidence</p>
                <p className="font-medium text-slate-900">{percent(result.confidence)}</p>
              </div>
            </div>

            <div>
              <p className="text-xs text-slate-400">Infrastructure</p>
              <p className="text-sm text-slate-700">{result.infrastructure_type}</p>
            </div>

            <div>
              <p className="text-xs text-slate-400">Summary</p>
              <p className="text-sm leading-relaxed text-slate-700">{result.summary}</p>
            </div>

            {result.recommended_action && (
              <div className="rounded-lg border border-ai-100 bg-ai-50 p-3">
                <p className="text-xs text-ai-600">Recommended action</p>
                <p className="mt-0.5 text-sm text-slate-800">{result.recommended_action}</p>
              </div>
            )}

            <div className="flex items-center justify-between">
              <span className="text-xs text-slate-400">
                {run?.model ? `model: ${run.model}` : ""}
              </span>
              <Button variant="outline" size="sm" onClick={analyze} disabled={running}>
                <AlertTriangle className="mr-1.5 h-4 w-4" /> Re-run
              </Button>
            </div>
          </motion.div>
        )}
      </CardContent>
    </Card>
  );
}