"use client";

import { Bot, Check, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import type { AiDraft } from "@/lib/conversation-api";

interface AiDraftModalProps {
  open: boolean;
  draft: AiDraft | null;
  loading: boolean;
  onUseReply: () => void;
  onClose: () => void;
}

export function AiDraftModal({
  open,
  draft,
  loading,
  onUseReply,
  onClose,
}: AiDraftModalProps) {
  return (
    <Modal open={open} onClose={onClose} title="AI conversation summary">
      {loading || !draft ? (
        <div className="space-y-3 py-4">
          <div className="h-4 w-1/2 animate-pulse rounded bg-slate-200" />
          <div className="h-3 w-full animate-pulse rounded bg-slate-100" />
          <div className="h-3 w-3/4 animate-pulse rounded bg-slate-100" />
          <div className="h-3 w-full animate-pulse rounded bg-slate-100" />
        </div>
      ) : (
        <div className="space-y-4">
          <div className="rounded-lg border border-primary-100 bg-primary-50/60 p-4">
            <div className="mb-1 flex items-center gap-1.5 text-xs font-semibold text-primary-700">
              <Sparkles className="h-3.5 w-3.5" />
              Summary
            </div>
            <p className="whitespace-pre-wrap text-sm leading-relaxed text-slate-700">
              {draft.summary}
            </p>
          </div>

          <div className="rounded-lg border border-border-soft bg-slate-50 p-4">
            <div className="mb-1 flex items-center gap-1.5 text-xs font-semibold text-slate-600">
              <Bot className="h-3.5 w-3.5" />
              Suggested reply
            </div>
            <p className="whitespace-pre-wrap text-sm leading-relaxed text-slate-700">
              {draft.suggested_reply}
            </p>
          </div>

          <p className="text-xs text-slate-400">
            This is an AI draft generated by {draft.generated_by} and is shown only for
            your review. It is never sent automatically — use the button below to load it
            into your own message, which is sent as you.
          </p>

          <div className="flex items-center justify-end gap-2">
            <Button variant="outline" onClick={onClose}>
              Discard
            </Button>
            <Button onClick={onUseReply}>
              <Check className="mr-2 h-4 w-4" />
              Use as my reply
            </Button>
          </div>
        </div>
      )}
    </Modal>
  );
}