"""Authenticated /media file serving (Part 28, 1F).

Local uploads (complaint evidence, conversation attachments) are streamed only
when the request carries either:
  1. a short-lived signed ``?token=`` (HMAC, generated by ``LocalStorage.url``),
     so browser ``<img>``/``<video>`` tags can still render evidence; or
  2. a valid Bearer access token (API / mobile clients).
Unsigned anonymous requests are rejected with 403.
"""

from __future__ import annotations

import os
import uuid

import jwt
from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.blacklist import is_blacklisted
from app.core.config import get_settings
from app.core.media_signing import verify_media_token
from app.core.security import decode_token
from app.db.session import get_db
from app.models import Complaint, ComplaintMedia, MessageAttachment, User, WorkOrder, WorkOrderPhoto
from app.storage.local import LocalStorage
from app.services.complaint_tracking_service import user_can_view

router = APIRouter(prefix="/media", tags=["media"])

_settings = get_settings()
_storage = LocalStorage(_settings)


def _denied() -> HTTPException:
    return HTTPException(
        status.HTTP_403_FORBIDDEN,
        "Media access requires a valid signed URL or an authenticated session.",
    )


async def _resolve_bearer(db: AsyncSession, raw_token: str) -> User | None:
    """Resolve a user from a raw access token; None for any invalid token."""
    try:
        claims = decode_token(raw_token, "access")
    except jwt.PyJWTError:
        return None
    if claims.get("jti") and await is_blacklisted(claims["jti"]):
        return None
    try:
        user_id = uuid.UUID(claims["sub"])
    except (ValueError, KeyError):
        return None
    user = await db.get(User, user_id)
    if user is None or not user.is_active:
        return None
    return user


async def _complaint_for_media_key(db: AsyncSession, key: str) -> Complaint | None:
    """Resolve the complaint that owns a media storage key, if any."""
    media = await db.scalar(
        select(ComplaintMedia).where(ComplaintMedia.storage_key == key)
    )
    if media is not None and media.complaint_id is not None:
        return await db.get(Complaint, media.complaint_id)

    photo = await db.scalar(
        select(WorkOrderPhoto).where(WorkOrderPhoto.storage_key == key)
    )
    if photo is not None:
        order = await db.get(WorkOrder, photo.work_order_id)
        if order is not None:
            return await db.get(Complaint, order.complaint_id)

    attachment = await db.scalar(
        select(MessageAttachment).where(MessageAttachment.storage_key == key)
    )
    if attachment is not None:
        return await db.get(Complaint, attachment.complaint_id)

    return None


@router.get("/{key:path}")
async def serve_media(
    key: str,
    request: Request,
    db: AsyncSession = Depends(get_db),
) -> FileResponse:
    if _settings.STORAGE_BACKEND.lower() != "local":
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Media not found.")

    signed = request.query_params.get("token", "")
    if signed and verify_media_token(
        key,
        signed,
        secret=_settings.JWT_SECRET,
        now=None,
        skew_seconds=_settings.MEDIA_ACCESS_SKEW_SECONDS,
    ):
        return await _file_response(key)

    auth = request.headers.get("authorization", "")
    if auth.lower().startswith("bearer "):
        user = await _resolve_bearer(db, auth[7:].strip())
        if user is not None:
            complaint = await _complaint_for_media_key(db, key)
            if complaint is not None and not user_can_view(user, complaint):
                raise HTTPException(
                    status.HTTP_403_FORBIDDEN,
                    "You do not have permission to access this media.",
                )
            return await _file_response(key)

    raise _denied()


async def _file_response(key: str) -> FileResponse:
    try:
        path = _storage.full_path(key)
    except ValueError as exc:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Invalid media key.") from exc
    if not os.path.isfile(path):
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Media not found.")
    return FileResponse(path, filename=os.path.basename(path))
