"""Predictive Hotspots service layer (Part 23, Part 36).

Facades the ML pipeline behind async, DB-bound operations:

* ``train_hotspots`` — loads REAL complaint records (user GPS or explicit manual
  map selection) from the database, builds the discrete-time training corpus and
  runs the time-aware training loop (CPU-bound, offloaded to a thread), writes
  the joblib artifact and records it in the ``predictive_models`` registry
  (exactly one active).
* ``get_status`` — exposes the active model + its evaluation metrics.
* ``get_predictions`` — live inference: real complaints (last 30 days) feed the
  same feature extractor the model was trained on; risk = P(>=1 complaint in
  the next ``horizon`` days) per grid cell, plus expected volume. Hotspot
  coordinates are the crowd centroids of the real complaint coordinates in each
  cell — never predefined, random or demo positions.

Hard guarantees (Part 36):

* Training data comes EXCLUSIVELY from complaint records stored in the database;
  complaint coordinates come from GPS or an explicitly user-selected map point.
* With zero complaints the surfaces report ``INSUFFICIENT_DATA`` (or "no model
  trained yet") and return zero cells — simply opening the hotspot page never
  creates a prediction.
* A model is only served when its bundle was trained on real complaints
  (``config.training_source == "real_complaints"``); legacy synthetic-trained
  artifacts are refused.
"""

from __future__ import annotations

import asyncio
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import Settings, get_settings
from app.ml.corpus import ComplaintEvent, corpus_from_events
from app.ml.external import LiveContextProvider, fetch_citywide_rainfall
from app.ml.grid import HotspotGrid
from app.ml.pipeline import (
    load_bundle,
    predict_from_bundle,
    run_training,
    save_bundle,
)
from app.ml.readiness import PredictionStatus, Readiness
from app.models import Complaint, ComplaintLocation, PredictiveModel, User, Ward
from app.models.enums import RoleName
from app.schemas.hotspots import (
    HotspotModelInfo,
    HotspotPredictions,
    HotspotStatus,
    HotspotTrainingOut,
    RiskCell,
)

_LIVE_LOOKBACK_DAYS = 30

# Rolling-feature warm-up (pipeline._WARMUP_DAYS) + margin so at least one
# snapshot window exists before the label horizon. Shorter real history is NOT
# trainable and the gate reports INSUFFICIENT_DATA.
_WARMUP_BUFFER_DAYS = 40

_DISCLAIMER = (
    "AI-predicted risk for the next 7 days, generated by the trained hotspot "
    "model. This is an AI prediction — NOT a confirmed incident. Risk scores "
    "combine real complaint patterns with contextual signals and may be wrong; "
    "validate any emerging issue before dispatching."
)


def _grid_from_settings(settings: Settings) -> HotspotGrid:
    min_lat, min_lon, max_lat, max_lon = [
        float(p) for p in settings.HOTSPOT_BBOX.split(",")
    ]
    return HotspotGrid(min_lat, min_lon, max_lat, max_lon, settings.HOTSPOT_CELL_DEG)


def _grid_from_bundle(bundle: dict) -> HotspotGrid:
    g = bundle["grid"]
    return HotspotGrid(g["min_lat"], g["min_lon"], g["max_lat"], g["max_lon"], g["cell_deg"])


def _artifact_path(settings: Settings, filename: str) -> Path:
    return Path(settings.HOTSPOT_ARTIFACT_DIR) / filename


def _category_name(category: object) -> str:
    return str(category.value) if hasattr(category, "value") else str(category)


# --------------------------------------------------------------------------- #
# Real-data loading
# --------------------------------------------------------------------------- #
async def _located_complaints(
    db: AsyncSession, since: datetime, *, with_category: bool = False
) -> list[tuple[datetime, object, float, float]]:
    """Real complaint rows with a non-null (lat, lon) — the only event source.

    Complaint coordinates are written at creation time from the citizen's GPS
    fix or their explicit manual map selection; nothing here invents positions.
    """
    cols = [Complaint.created_at, ComplaintLocation.latitude, ComplaintLocation.longitude]
    if with_category:
        cols.insert(1, Complaint.category)
    rows = (
        await db.execute(
            select(*cols)
            .join(ComplaintLocation, ComplaintLocation.complaint_id == Complaint.id)
            .where(
                Complaint.created_at >= since,
                ComplaintLocation.latitude.is_not(None),
                ComplaintLocation.longitude.is_not(None),
            )
        )
    ).all()
    return [tuple(r) for r in rows]  # type: ignore[return-value]


async def _readiness(db: AsyncSession, grid: HotspotGrid, settings: Settings) -> Readiness:
    """Count REAL complaint history that maps into the grid (Part 31 gating).

    ``records`` = located complaints inside the grid within the gating lookback;
    ``area_time_observations`` = distinct (grid cell, day) buckets from that
    history. A synthetic-free gate: zero records => never ready.
    """
    since = datetime.now(UTC) - timedelta(days=settings.ML_GATING_LOOKBACK_DAYS)
    records = 0
    days: set[tuple[str, object]] = set()
    for created_at, lat, lon in await _located_complaints(db, since):
        cell = grid.cell_id(lat, lon)
        if cell is None:
            continue
        records += 1
        days.add((cell, created_at.date()))
    return Readiness(
        records=records,
        area_time_observations=len(days),
        minimum_records=settings.MINIMUM_TRAINING_RECORDS,
        minimum_observations=settings.MINIMUM_AREA_TIME_OBSERVATIONS,
    )


async def _historical_events(
    db: AsyncSession, grid: HotspotGrid, settings: Settings
) -> list[ComplaintEvent]:
    """Bucket real complaint records (training lookback) into grid cells."""
    since = datetime.now(UTC) - timedelta(days=settings.HOTSPOT_TRAIN_LOOKBACK_DAYS)
    events: list[ComplaintEvent] = []
    for created_at, category, lat, lon in await _located_complaints(
        db, since, with_category=True
    ):
        cell = grid.cell_id(lat, lon)
        if cell is None:
            continue
        events.append(
            ComplaintEvent(
                ts=created_at,
                cell_id=cell,
                latitude=lat,
                longitude=lon,
                category=_category_name(category),
            )
        )
    return events


# --------------------------------------------------------------------------- #
# Training
# --------------------------------------------------------------------------- #
def _train_sync(
    settings: Settings,
    grid: HotspotGrid,
    corpus,
    context_provider,
) -> dict:
    return run_training(settings, grid, corpus, context_provider)


async def train_hotspots(
    db: AsyncSession,
    user: User | None,
    settings: Settings | None = None,
) -> HotspotTrainingOut:
    settings = settings or get_settings()
    grid = _grid_from_settings(settings)

    # Part 31 gate: refuse to train on thin real history.
    readiness = await _readiness(db, grid, settings)
    if not readiness.ready:
        return HotspotTrainingOut(
            trained=False,
            status=PredictionStatus.INSUFFICIENT_DATA,
            message=readiness.message("The predictive hotspot model"),
            records_available=readiness.records,
            observations_available=readiness.area_time_observations,
            minimum_records=readiness.minimum_records,
            minimum_observations=readiness.minimum_observations,
        )

    # Training is fed ONLY by real complaint records from the database.
    events = await _historical_events(db, grid, settings)
    if not events:
        return HotspotTrainingOut(
            trained=False,
            status=PredictionStatus.INSUFFICIENT_DATA,
            message=(
                "No located complaints exist inside the hotspot grid within the "
                "training lookback; the model is only ever trained on real "
                "complaint records."
            ),
            records_available=readiness.records,
            observations_available=readiness.area_time_observations,
            minimum_records=readiness.minimum_records,
            minimum_observations=readiness.minimum_observations,
        )

    # Rolling features need a warm-up window plus the label horizon; a burst
    # confined to a few days does not form a supervised time series.
    span_days = (max(e.ts for e in events) - min(e.ts for e in events)).days
    span_days = max(0, span_days)
    if span_days < settings.HOTSPOT_HORIZON_DAYS + _WARMUP_BUFFER_DAYS:
        return HotspotTrainingOut(
            trained=False,
            status=PredictionStatus.INSUFFICIENT_DATA,
            message=(
                "Real complaint history is still too compressed to train: it must "
                f"span at least {settings.HOTSPOT_HORIZON_DAYS + _WARMUP_BUFFER_DAYS} "
                "days so rolling features and label windows are well-formed."
            ),
            records_available=readiness.records,
            observations_available=readiness.area_time_observations,
            minimum_records=readiness.minimum_records,
            minimum_observations=readiness.minimum_observations,
        )

    # Real context provider: ward residents + currently-available rainfall.
    population, _ward_map = await _population_and_ward_map(db, grid)
    rain_mm, rain_available = await fetch_citywide_rainfall(settings)
    provider = LiveContextProvider(
        settings,
        population_per_cell=population,
        rain_mm=rain_mm,
        rain_available=rain_available,
    ).provider()

    started = time.monotonic()
    # CPU-bound (dataframe + XGBoost); offload so the event loop stays responsive.
    bundle = await asyncio.to_thread(
        _train_sync, settings, grid, corpus_from_events(events), provider
    )
    duration = round(time.monotonic() - started, 2)

    version = await _next_version(db)
    filename = f"hotspot_v{version}.joblib"
    path = _artifact_path(settings, filename)
    path.parent.mkdir(parents=True, exist_ok=True)
    await asyncio.to_thread(save_bundle, bundle, str(path))

    await db.execute(
        update(PredictiveModel).where(PredictiveModel.is_active.is_(True)).values(is_active=False)
    )
    row = PredictiveModel(
        version=version,
        kind=bundle["kind"],
        artifact_filename=filename,
        metrics=bundle["metrics"],
        config=bundle["config"],
        status="ready",
        is_active=True,
        trained_by_user_id=user.id if user else None,
        trained_at=datetime.now(UTC),
    )
    db.add(row)
    await db.commit()
    await db.refresh(row)

    return HotspotTrainingOut(
        trained=True,
        status=PredictionStatus.READY,
        version=version,
        model=_model_info(row),
        metrics=bundle["metrics"],
        config=bundle["config"],
        rows=bundle["config"]["training_rows"],
        duration_seconds=duration,
        message="Hotspot model trained exclusively on real complaint records.",
    )


async def _next_version(db: AsyncSession) -> int:
    last = await db.scalar(select(func.max(PredictiveModel.version)))
    return int(last) + 1 if last else 1


def _model_info(row: PredictiveModel) -> HotspotModelInfo:
    return HotspotModelInfo(
        version=row.version,
        kind=row.kind,
        status=row.status,
        is_active=row.is_active,
        trained_at=row.trained_at,
        artifact_filename=row.artifact_filename,
        metrics=row.metrics or {},
        config=row.config or {},
    )


def _is_real_source(row: PredictiveModel) -> bool:
    """Only models trained on this platform's real complaint data may serve."""
    return bool(row.config and row.config.get("training_source") == "real_complaints")


def _not_real_model_message() -> str:
    return (
        "The registered hotspot model was not trained on this platform's real "
        "complaint data and cannot be served. Retrain with POST /api/v1/hotspots/train."
    )


# --------------------------------------------------------------------------- #
# Status
# --------------------------------------------------------------------------- #
async def get_status(
    db: AsyncSession,
    settings: Settings | None = None,
) -> HotspotStatus:
    settings = settings or get_settings()
    grid = _grid_from_settings(settings)
    readiness = await _readiness(db, grid, settings)
    row = await db.scalar(select(PredictiveModel).where(PredictiveModel.is_active.is_(True)))
    if row is None:
        return HotspotStatus(
            trained=False,
            prediction_status=readiness.status,
            model=None,
            message=readiness.message("The predictive hotspot model"),
            records_available=readiness.records,
            observations_available=readiness.area_time_observations,
            minimum_records=readiness.minimum_records,
            minimum_observations=readiness.minimum_observations,
        )
    if not readiness.ready:
        # A model exists but current real data is too thin to serve it.
        return HotspotStatus(
            trained=True,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=_model_info(row),
            message=readiness.message("The predictive hotspot model"),
            records_available=readiness.records,
            observations_available=readiness.area_time_observations,
            minimum_records=readiness.minimum_records,
            minimum_observations=readiness.minimum_observations,
        )
    if not _is_real_source(row):
        return HotspotStatus(
            trained=True,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=_model_info(row),
            message=_not_real_model_message(),
            records_available=readiness.records,
            observations_available=readiness.area_time_observations,
            minimum_records=readiness.minimum_records,
            minimum_observations=readiness.minimum_observations,
        )
    return HotspotStatus(
        trained=True,
        prediction_status=PredictionStatus.READY,
        model=_model_info(row),
        message="Active predictive hotspot model, forecasts are being served.",
        records_available=readiness.records,
        observations_available=readiness.area_time_observations,
        minimum_records=readiness.minimum_records,
        minimum_observations=readiness.minimum_observations,
    )


# --------------------------------------------------------------------------- #
# Live inference
# --------------------------------------------------------------------------- #
async def _live_events(db: AsyncSession, grid: HotspotGrid) -> tuple[list[ComplaintEvent], int]:
    """Real complaints from the last N days, bucketed into grid cells."""
    since = datetime.now(UTC) - timedelta(days=_LIVE_LOOKBACK_DAYS)
    events: list[ComplaintEvent] = []
    outside = 0
    for created_at, category, lat, lon in await _located_complaints(
        db, since, with_category=True
    ):
        cell = grid.cell_id(lat, lon)
        if cell is None:
            outside += 1
            continue
        events.append(
            ComplaintEvent(
                ts=created_at,
                cell_id=cell,
                latitude=lat,
                longitude=lon,
                category=_category_name(category),
            )
        )
    return events, outside


def _crowd_centroids(events: list[ComplaintEvent]) -> dict[str, tuple[float, float]]:
    """Mean real complaint coordinate per cell — the hotspot's geographic anchor.

    Hotspot positions are therefore *calculated from the actual complaint
    coordinates* (grid centroids only when a cell has no live events at all).
    """
    totals: dict[str, list[tuple[float, float]]] = {}
    for e in events:
        totals.setdefault(e.cell_id, []).append((e.latitude, e.longitude))
    out: dict[str, tuple[float, float]] = {}
    for cell, points in totals.items():
        n = len(points)
        out[cell] = (
            round(sum(p[0] for p in points) / n, 6),
            round(sum(p[1] for p in points) / n, 6),
        )
    return out


async def _population_and_ward_map(
    db: AsyncSession,
    grid: HotspotGrid,
) -> tuple[dict[str, float], dict[str, dict]]:
    """Resident-count proxy per cell + cell -> {ward_code, ward_name} via PostGIS."""
    geo = _geo_service()
    counts_rows = (
        await db.execute(
            select(Ward.id, Ward.code, Ward.name, func.count(User.id).label("residents"))
            .join(User, User.ward_id == Ward.id)
            .group_by(Ward.id, Ward.code, Ward.name)
        )
    ).all()
    counts = {str(wid): int(res) for wid, _code, _name, res in counts_rows}

    population: dict[str, float] = {}
    ward_map: dict[str, dict] = {}
    for cell in grid.all_cells():
        lat, lon = grid.cell_centroid(cell)
        detected = await geo.find_ward(db, lat, lon)
        if detected is not None:
            ward_map[cell] = {"ward_code": detected.code, "ward_name": detected.name}
            population[cell] = counts.get(str(detected.ward_id), 0.0)
    return population, ward_map


def _geo_service():
    from app.services.geo_service import GeoService

    return GeoService()


async def get_predictions(
    db: AsyncSession,
    user: User,
    settings: Settings | None = None,
) -> HotspotPredictions:
    settings = settings or get_settings()
    grid = _grid_from_settings(settings)

    # Part 31 gate: forecasts are only served once real complaint history clears
    # the minimum thresholds. No lazy provisioning — a thin DB must STAY empty.
    readiness = await _readiness(db, grid, settings)
    if not readiness.ready:
        return HotspotPredictions(
            ai_prediction=True,
            disclaimer=_DISCLAIMER,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=None,
            cells=[],
            message=readiness.message("The predictive hotspot model"),
            records_available=readiness.records,
            observations_available=readiness.area_time_observations,
            minimum_records=readiness.minimum_records,
            minimum_observations=readiness.minimum_observations,
        )

    row = await db.scalar(select(PredictiveModel).where(PredictiveModel.is_active.is_(True)))
    if row is None:
        # Enough REAL data exists, but no model is trained. The hotspot page
        # must NEVER train one on its own: an authorized officer triggers the
        # explicit training action.
        return HotspotPredictions(
            ai_prediction=True,
            disclaimer=_DISCLAIMER,
            prediction_status=PredictionStatus.READY,
            model=None,
            cells=[],
            message=(
                "Real complaint history clears the minimum for training, but no "
                "hotspot model is trained yet. An authorized officer must train it "
                "(POST /api/v1/hotspots/train) — forecasts are never created just "
                "because this page was opened."
            ),
            records_available=readiness.records,
            observations_available=readiness.area_time_observations,
            minimum_records=readiness.minimum_records,
            minimum_observations=readiness.minimum_observations,
        )
    if not _is_real_source(row):
        # Defense-in-depth: a registry row pointing at a synthetic-trained
        # artifact can never serve forecasts.
        return HotspotPredictions(
            ai_prediction=True,
            disclaimer=_DISCLAIMER,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=_model_info(row),
            cells=[],
            message=_not_real_model_message(),
            records_available=readiness.records,
            observations_available=readiness.area_time_observations,
            minimum_records=readiness.minimum_records,
            minimum_observations=readiness.minimum_observations,
        )

    bundle = await asyncio.to_thread(
        load_bundle, str(_artifact_path(settings, row.artifact_filename))
    )
    grid = _grid_from_bundle(bundle)

    events, outside = await _live_events(db, grid)

    population, ward_map = await _population_and_ward_map(db, grid)
    rain_mm, rain_available = await fetch_citywide_rainfall(settings)
    provider = LiveContextProvider(
        settings,
        population_per_cell=population,
        rain_mm=rain_mm,
        rain_available=rain_available,
    ).provider()

    from app.ml.features import build_feature_frame

    reference = datetime.now(UTC)
    row_frame = await asyncio.to_thread(
        build_feature_frame,
        events,
        [reference],
        grid,
        provider,
        horizon_days=bundle["config"]["horizon_days"],
    )

    proba, volume = await asyncio.to_thread(predict_from_bundle, bundle, row_frame)
    proba = proba.tolist()
    volume = volume.tolist()

    observed = _observed_trailing7(events)
    crowd = _crowd_centroids(events)

    cells: list[RiskCell] = []
    for i, cell in enumerate([c["cell_id"] for c in bundle["grid"]["cells"]]):
        # Reported hotspot position = crowd centroid of the real complaints in
        # that cell; grid centroids only fall back when the cell has no live
        # events (the model's risk still derives from real historical data).
        centroid_lat, centroid_lon = crowd.get(
            cell,
            (bundle["grid"]["cells"][i]["latitude"], bundle["grid"]["cells"][i]["longitude"]),
        )
        risk = float(proba[i])
        tier = "high" if risk >= 0.5 else ("medium" if risk >= 0.25 else "low")
        w = ward_map.get(cell, {})
        cells.append(
            RiskCell(
                cell_id=cell,
                latitude=centroid_lat,
                longitude=centroid_lon,
                risk_score=round(risk, 4),
                expected_volume=round(max(0.0, float(volume[i])), 3),
                tier=tier,
                ward_code=w.get("ward_code"),
                ward_name=w.get("ward_name"),
                trailing7=observed.get(cell, 0),
            )
        )
    cells.sort(key=lambda c: c.risk_score, reverse=True)

    # WARD_REPRESENTATIVE: forecasts are ALWAYS filtered to the caller's own
    # ward. The model is city-wide, but a representative must never see another
    # ward's predicted cells. An unassigned representative sees nothing.
    message = "Forecasts served from the trained hotspot model (real complaints only)."
    if user.role.name == RoleName.WARD_REPRESENTATIVE.value:
        if user.ward_id is None:
            cells = []
            message = (
                "Your ward representative account is not assigned to a ward yet, "
                "so no ward-scoped forecasts can be shown."
            )
        else:
            ward = await db.get(Ward, user.ward_id)
            ward_code = ward.code if ward is not None else None
            if ward_code is None:
                cells = []
                message = "Your assigned ward could not be resolved, so no forecasts are shown."
            else:
                cells = [c for c in cells if c.ward_code == ward_code]
                message = (
                    f"Forecasts are served for your ward ({ward_code}) from the trained "
                    "hotspot model (real complaints only)."
                )

    return HotspotPredictions(
        ai_prediction=True,
        disclaimer=_DISCLAIMER,
        prediction_status=PredictionStatus.READY,
        horizon_days=bundle["config"]["horizon_days"],
        inference_at=reference,
        model=_model_info(row),
        cells=cells,
        population_cells=len(population),
        complaint_events_used=len(events),
        complaints_outside_grid=outside,
        message=message,
        records_available=readiness.records,
        observations_available=readiness.area_time_observations,
        minimum_records=readiness.minimum_records,
        minimum_observations=readiness.minimum_observations,
    )


def _observed_trailing7(events: list[ComplaintEvent]) -> dict[str, int]:
    cutoff = datetime.now(UTC) - timedelta(days=7)
    out: dict[str, int] = {}
    for e in events:
        if e.ts >= cutoff:
            out[e.cell_id] = out.get(e.cell_id, 0) + 1
    return out
