"""Predictive Hotspots service layer (Part 23).

Facades the ML pipeline behind async, DB-bound operations:

* ``train_hotspots`` — builds the deterministic corpus, runs the time-aware
  training loop (CPU-bound, offloaded to a thread), writes the joblib artifact
  and records it in the ``predictive_models`` registry (exactly one active).
* ``get_status`` — exposes the active model + its evaluation metrics.
* ``get_predictions`` — live inference: real complaints (last 30 days) feed the
  same feature extractor the model was trained on; risk = P(>=1 complaint in
  the next ``horizon`` days) per grid cell, plus expected volume. If no model
  has been trained yet it trains one lazily (first call).
"""

from __future__ import annotations

import asyncio
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import Settings, get_settings
from app.ml.corpus import ComplaintEvent, build_corpus
from app.ml.external import LiveContextProvider, fetch_citywide_rainfall
from app.ml.grid import HotspotGrid
from app.ml.pipeline import (
    load_bundle,
    predict_from_bundle,
    run_training,
    save_bundle,
)
from app.models import Complaint, ComplaintLocation, PredictiveModel, User, Ward
from app.schemas.hotspots import (
    HotspotModelInfo,
    HotspotPredictions,
    HotspotStatus,
    HotspotTrainingOut,
    RiskCell,
)

_LIVE_LOOKBACK_DAYS = 30

_DISCLAIMER = (
    "AI-predicted risk for the next 7 days, generated by the trained hotspot "
    "model. This is a forecast, NOT a list of confirmed incidents. Risk scores "
    "combine historical complaint patterns with contextual signals and may be "
    "wrong; validate any emerging issue before dispatching."
)


def _grid_from_settings(settings: Settings) -> HotspotGrid:
    min_lat, min_lon, max_lat, max_lon = [
        float(p) for p in settings.HOTSPOT_BBOX.split(",")
    ]
    return HotspotGrid(min_lat, min_lon, max_lat, max_lon, settings.HOTSPOT_CELL_DEG)


def _grid_from_bundle(bundle: dict) -> HotspotGrid:
    g = bundle["grid"]
    return HotspotGrid(g["min_lat"], g["min_lon"], g["max_lat"], g["max_lon"], g["cell_deg"])


def _artifact_path(settings: Settings, filename: str) -> Path:
    return Path(settings.HOTSPOT_ARTIFACT_DIR) / filename


# --------------------------------------------------------------------------- #
# Training
# --------------------------------------------------------------------------- #
def _train_sync(settings: Settings) -> dict:
    grid = _grid_from_settings(settings)
    corpus = build_corpus(grid, settings.HOTSPOT_CORPUS_YEARS, settings.HOTSPOT_CORPUS_SEED)
    return run_training(settings, grid, corpus, corpus.context_provider())


async def train_hotspots(
    db: AsyncSession,
    user: User | None,
    settings: Settings | None = None,
) -> HotspotTrainingOut:
    settings = settings or get_settings()
    started = time.monotonic()
    # CPU-bound (dataframe + XGBoost); offload so the event loop stays responsive.
    bundle = await asyncio.to_thread(_train_sync, settings)
    duration = round(time.monotonic() - started, 2)

    version = await _next_version(db)
    filename = f"hotspot_v{version}.joblib"
    path = _artifact_path(settings, filename)
    path.parent.mkdir(parents=True, exist_ok=True)
    await asyncio.to_thread(save_bundle, bundle, str(path))

    await db.execute(
        update(PredictiveModel).where(PredictiveModel.is_active.is_(True)).values(is_active=False)
    )
    row = PredictiveModel(
        version=version,
        kind=bundle["kind"],
        artifact_filename=filename,
        metrics=bundle["metrics"],
        config=bundle["config"],
        status="ready",
        is_active=True,
        trained_by_user_id=user.id if user else None,
        trained_at=datetime.now(UTC),
    )
    db.add(row)
    await db.commit()
    await db.refresh(row)

    return HotspotTrainingOut(
        trained=True,
        version=version,
        model=_model_info(row),
        metrics=bundle["metrics"],
        config=bundle["config"],
        rows=bundle["config"]["training_rows"],
        duration_seconds=duration,
    )


async def _next_version(db: AsyncSession) -> int:
    last = await db.scalar(select(func.max(PredictiveModel.version)))
    return int(last) + 1 if last else 1


def _model_info(row: PredictiveModel) -> HotspotModelInfo:
    return HotspotModelInfo(
        version=row.version,
        kind=row.kind,
        status=row.status,
        is_active=row.is_active,
        trained_at=row.trained_at,
        artifact_filename=row.artifact_filename,
        metrics=row.metrics or {},
        config=row.config or {},
    )


# --------------------------------------------------------------------------- #
# Status
# --------------------------------------------------------------------------- #
async def get_status(
    db: AsyncSession,
    settings: Settings | None = None,
) -> HotspotStatus:
    settings = settings or get_settings()
    row = await db.scalar(select(PredictiveModel).where(PredictiveModel.is_active.is_(True)))
    if row is None:
        return HotspotStatus(
            trained=False,
            model=None,
            message=(
                "No predictive hotspot model is trained yet. The first "
                "predictions request trains one (this can take a minute)."
            ),
        )
    return HotspotStatus(
        trained=True,
        model=_model_info(row),
        message="Active predictive hotspot model (synthetic corpus training, live inference).",
    )


# --------------------------------------------------------------------------- #
# Live inference
# --------------------------------------------------------------------------- #
async def _live_events(db: AsyncSession, grid: HotspotGrid) -> tuple[list[ComplaintEvent], int]:
    """Real complaints from the last N days, bucketed into grid cells."""
    since = datetime.now(UTC) - timedelta(days=_LIVE_LOOKBACK_DAYS)
    rows = (
        await db.execute(
            select(
                Complaint.created_at,
                Complaint.category,
                ComplaintLocation.latitude,
                ComplaintLocation.longitude,
            )
            .join(ComplaintLocation, ComplaintLocation.complaint_id == Complaint.id)
            .where(
                Complaint.created_at >= since,
                ComplaintLocation.latitude.is_not(None),
                ComplaintLocation.longitude.is_not(None),
            )
        )
    ).all()
    events: list[ComplaintEvent] = []
    outside = 0
    for created_at, category, lat, lon in rows:
        cell = grid.cell_id(lat, lon)
        if cell is None:
            outside += 1
            continue
        events.append(
            ComplaintEvent(
                ts=created_at.replace(tzinfo=UTC) if created_at.tzinfo is None else created_at,
                cell_id=cell,
                latitude=lat,
                longitude=lon,
                category=str(category.value) if hasattr(category, "value") else str(category),
            )
        )
    return events, outside


async def _population_and_ward_map(
    db: AsyncSession,
    grid: HotspotGrid,
) -> tuple[dict[str, float], dict[str, dict]]:
    """Resident-count proxy per cell + cell -> {ward_code, ward_name} via PostGIS."""
    geo = await _geo_service()
    counts_rows = (
        await db.execute(
            select(Ward.id, Ward.code, Ward.name, func.count(User.id).label("residents"))
            .join(User, User.ward_id == Ward.id)
            .group_by(Ward.id, Ward.code, Ward.name)
        )
    ).all()
    counts = {str(wid): int(res) for wid, _code, _name, res in counts_rows}

    population: dict[str, float] = {}
    ward_map: dict[str, dict] = {}
    for cell in grid.all_cells():
        lat, lon = grid.cell_centroid(cell)
        detected = await geo.find_ward(db, lat, lon)
        if detected is not None:
            ward_map[cell] = {"ward_code": detected.code, "ward_name": detected.name}
            population[cell] = counts.get(str(detected.ward_id), 0.0)
    return population, ward_map


async def _geo_service():
    from app.services.geo_service import GeoService

    return GeoService()


async def get_predictions(
    db: AsyncSession,
    user: User,
    settings: Settings | None = None,
) -> HotspotPredictions:
    settings = settings or get_settings()
    row = await db.scalar(select(PredictiveModel).where(PredictiveModel.is_active.is_(True)))
    if row is None:
        # Lazy provisioning: first predictions request trains the model.
        await train_hotspots(db, user, settings)
        row = await db.scalar(select(PredictiveModel).where(PredictiveModel.is_active.is_(True)))
        if row is None:
            raise RuntimeError("Predictive hotspot training failed to produce an active model")

    bundle = await asyncio.to_thread(
        load_bundle, str(_artifact_path(settings, row.artifact_filename))
    )
    grid = _grid_from_bundle(bundle)

    events, outside = await _live_events(db, grid)

    population, ward_map = await _population_and_ward_map(db, grid)
    rain_mm, rain_available = await fetch_citywide_rainfall(settings)
    provider = LiveContextProvider(
        settings,
        population_per_cell=population,
        rain_mm=rain_mm,
        rain_available=rain_available,
    ).provider()

    from app.ml.features import build_feature_frame

    reference = datetime.now(UTC)
    row_frame = await asyncio.to_thread(
        build_feature_frame,
        events,
        [reference],
        grid,
        provider,
        horizon_days=bundle["config"]["horizon_days"],
    )

    proba, volume = await asyncio.to_thread(predict_from_bundle, bundle, row_frame)
    proba = proba.tolist()
    volume = volume.tolist()

    observed = _observed_trailing7(events)

    cells: list[RiskCell] = []
    for i, cell in enumerate([c["cell_id"] for c in bundle["grid"]["cells"]]):
        lat_ = bundle["grid"]["cells"][i]["latitude"]
        lon_ = bundle["grid"]["cells"][i]["longitude"]
        risk = float(proba[i])
        tier = "high" if risk >= 0.5 else ("medium" if risk >= 0.25 else "low")
        w = ward_map.get(cell, {})
        cells.append(
            RiskCell(
                cell_id=cell,
                latitude=round(lat_, 6),
                longitude=round(lon_, 6),
                risk_score=round(risk, 4),
                expected_volume=round(max(0.0, float(volume[i])), 3),
                tier=tier,
                ward_code=w.get("ward_code"),
                ward_name=w.get("ward_name"),
                trailing7=observed.get(cell, 0),
            )
        )
    cells.sort(key=lambda c: c.risk_score, reverse=True)

    return HotspotPredictions(
        ai_prediction=True,
        disclaimer=_DISCLAIMER,
        horizon_days=bundle["config"]["horizon_days"],
        inference_at=reference,
        model=_model_info(row),
        cells=cells,
        population_cells=len(population),
        complaint_events_used=len(events),
        complaints_outside_grid=outside,
    )


def _observed_trailing7(events: list[ComplaintEvent]) -> dict[str, int]:
    cutoff = datetime.now(UTC) - timedelta(days=7)
    out: dict[str, int] = {}
    for e in events:
        if e.ts >= cutoff:
            out[e.cell_id] = out.get(e.cell_id, 0) + 1
    return out
