"""Predictive Infrastructure Maintenance service layer (Part 24).

Facades the infra ML pipeline behind async, DB-bound operations:

* ``train`` - builds the deterministic synthetic asset corpus, runs the
  time-aware training loop (offloaded to a thread), writes the joblib artifact
  and records it in the ``infrastructure_models`` registry (exactly one active).
* ``get_status`` - exposes the active infra model + its evaluation metrics.
* ``list_assets`` / ``register_asset`` - asset registry management.
* ``get_predictions`` - live inference: real asset records, nearby complaints,
  repair history, ward population and (optionally) rainfall feed the same
  feature extractor the model was trained on; risk = P(failure within the
  horizon). Every output is flagged ``ai_prediction`` and phrased as predicted
  risk / recommended inspection.
* ``review_prediction`` / ``create_preventive_work_order`` - the officer review
  workflow and the optional preventive work order raised on an approved asset.
"""

from __future__ import annotations

import asyncio
import math
import time
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pandas as pd
from fastapi import HTTPException, status
from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import Settings, get_settings
from app.ml.external import fetch_infra_citywide_rainfall
from app.ml.infra_features import (
    age_years,
    build_feature_dict,
    feature_columns,
    recommend_action_text,
    recommendation_for,
    risk_level_for_probability,
    supporting_factors_for,
)
from app.ml.infra_pipeline import (
    load_bundle,
    predict_from_bundle,
    run_infra_training,
    save_bundle,
)
from app.ml.readiness import PredictionStatus
from app.models import (
    Complaint,
    ComplaintLocation,
    InfrastructureAsset,
    InfrastructureModel,
    InfrastructurePrediction,
    PreventiveWorkOrder,
    User,
    Ward,
    WorkOrder,
)
from app.models.enums import (
    InfrastructureCategory,
    PredictionReviewStatus,
    PreventiveWorkOrderStatus,
)
from app.schemas.infrastructure import (
    AssetPrediction,
    InfrastructureAssetIn,
    InfrastructureAssetOut,
    InfrastructureModelInfo,
    InfrastructurePredictions,
    InfrastructureReviewOut,
    InfrastructureStatus,
    InfrastructureTrainingOut,
    PreventiveWorkOrderOut,
)

_DISCLAIMER = (
    "AI-predicted maintenance risk for infrastructure assets, generated by the "
    "trained infrastructure model. This is a forecast, NOT a confirmed list of "
    "failing assets. Probabilities blend historical complaints, repair history, "
    "asset age, weather and location signals and may be wrong; verify any "
    "at-risk asset before dispatching."
)

_EXPECTED_REVIEW_DECISIONS = {
    PredictionReviewStatus.APPROVED.value,
    PredictionReviewStatus.REJECTED.value,
}


def _artifact_path(settings: Settings, filename: str) -> Path:
    return Path(settings.INFRA_ARTIFACT_DIR) / filename


# --------------------------------------------------------------------------- #
# Training / status
# --------------------------------------------------------------------------- #
async def _train_sync(settings: Settings) -> dict:
    return await asyncio.to_thread(run_infra_training, settings)


async def _next_version(db: AsyncSession) -> int:
    last = await db.scalar(select(func.max(InfrastructureModel.version)))
    return int(last) + 1 if last else 1


def _model_info(row: InfrastructureModel) -> InfrastructureModelInfo:
    return InfrastructureModelInfo(
        version=row.version,
        kind=row.kind,
        status=row.status,
        is_active=row.is_active,
        trained_at=row.trained_at,
        artifact_filename=row.artifact_filename,
        metrics=row.metrics or {},
        config=row.config or {},
    )


async def _asset_count(db: AsyncSession) -> int:
    return int(
        await db.scalar(
            select(func.count(InfrastructureAsset.id)).where(InfrastructureAsset.is_active.is_(True))
        )
        or 0
    )


async def get_status(
    db: AsyncSession,
    settings: Settings | None = None,
) -> InfrastructureStatus:
    settings = settings or get_settings()
    registered = await _asset_count(db)
    row = await db.scalar(
        select(InfrastructureModel).where(InfrastructureModel.is_active.is_(True))
    )
    if row is None:
        return InfrastructureStatus(
            trained=False,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=None,
            message=_infra_gate_message(registered, settings.INFRA_MIN_ASSETS),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
        )
    if registered < settings.INFRA_MIN_ASSETS:
        return InfrastructureStatus(
            trained=True,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=_model_info(row),
            message=_infra_gate_message(registered, settings.INFRA_MIN_ASSETS),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
        )
    return InfrastructureStatus(
        trained=True,
        prediction_status=PredictionStatus.READY,
        model=_model_info(row),
        message="Active predictive infrastructure model, forecasts are being served.",
        registered_assets=registered,
        minimum_assets=settings.INFRA_MIN_ASSETS,
    )


def _infra_gate_message(registered: int, minimum: int) -> str:
    return (
        "The infrastructure model is not ready yet: "
        f"{registered}/{minimum} registered assets are required. Register real "
        "assets in the asset registry before forecasts are enabled."
    )


async def train(
    db: AsyncSession,
    user: User | None,
    settings: Settings | None = None,
) -> InfrastructureTrainingOut:
    settings = settings or get_settings()

    # Part 31 gate: refuse to train without a real, on-the-books fleet.
    registered = await _asset_count(db)
    if registered < settings.INFRA_MIN_ASSETS:
        return InfrastructureTrainingOut(
            trained=False,
            status=PredictionStatus.INSUFFICIENT_DATA,
            message=_infra_gate_message(registered, settings.INFRA_MIN_ASSETS),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
        )

    started = time.monotonic()
    bundle = await _train_sync(settings)
    duration = round(time.monotonic() - started, 2)

    version = await _next_version(db)
    filename = f"infrastructure_v{version}.joblib"
    path = _artifact_path(settings, filename)
    path.parent.mkdir(parents=True, exist_ok=True)
    await asyncio.to_thread(save_bundle, bundle, str(path))

    await db.execute(
        update(InfrastructureModel)
        .where(InfrastructureModel.is_active.is_(True))
        .values(is_active=False)
    )
    row = InfrastructureModel(
        version=version,
        kind=bundle["kind"],
        artifact_filename=filename,
        metrics=bundle["metrics"],
        config=bundle["config"],
        status="ready",
        is_active=True,
        trained_by_user_id=user.id if user else None,
        trained_at=datetime.now(UTC),
    )
    db.add(row)
    await db.commit()
    await db.refresh(row)

    return InfrastructureTrainingOut(
        trained=True,
        status=PredictionStatus.READY,
        version=version,
        model=_model_info(row),
        metrics=bundle["metrics"],
        config=bundle["config"],
        rows=bundle["config"]["training_rows"],
        duration_seconds=duration,
        message="Infrastructure model trained on the configured asset corpus.",
        registered_assets=registered,
        minimum_assets=settings.INFRA_MIN_ASSETS,
    )


# --------------------------------------------------------------------------- #
# Asset registry
# --------------------------------------------------------------------------- #
def _asset_out(asset: InfrastructureAsset) -> InfrastructureAssetOut:
    ward = asset.ward
    return InfrastructureAssetOut(
        id=str(asset.id),
        name=asset.name,
        category=asset.category.value if hasattr(asset.category, "value") else str(asset.category),
        ward_id=str(asset.ward_id) if asset.ward_id else None,
        ward_code=ward.code if ward else None,
        ward_name=ward.name if ward else None,
        latitude=asset.latitude,
        longitude=asset.longitude,
        address=asset.address,
        installed_at=asset.installed_at,
        condition_note=asset.condition_note,
        is_active=asset.is_active,
        created_at=asset.created_at,
    )


async def list_assets(db: AsyncSession) -> list[InfrastructureAssetOut]:
    rows = (
        await db.execute(
            select(InfrastructureAsset)
            .options(selectinload(InfrastructureAsset.ward))
            .where(InfrastructureAsset.is_active.is_(True))
            .order_by(InfrastructureAsset.created_at.asc())
        )
    ).scalars().all()
    return [_asset_out(a) for a in rows]


async def register_asset(
    db: AsyncSession, payload: InfrastructureAssetIn
) -> InfrastructureAssetOut:
    if payload.category not in InfrastructureCategory.__members__:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Unknown infrastructure category: {payload.category}",
)
    asset = InfrastructureAsset(
        name=payload.name,
        category=InfrastructureCategory(payload.category),
        ward_id=uuid.UUID(payload.ward_id) if payload.ward_id else None,
        latitude=payload.latitude,
        longitude=payload.longitude,
        address=payload.address,
        installed_at=payload.installed_at,
        condition_note=payload.condition_note,
        is_active=True,
    )
    db.add(asset)
    await db.commit()
    await db.refresh(asset)
    # Resolve the ward eagerly so the response schema never lazy-loads.
    if asset.ward_id:
        asset.ward = await db.get(Ward, asset.ward_id)
    return _asset_out(asset)


# --------------------------------------------------------------------------- #
# Live inference
# --------------------------------------------------------------------------- #
def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371.0088
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def _count_near(
    lat: float | None,
    lon: float | None,
    points: list[tuple[float, float]],
    radius_km: float,
) -> int:
    if lat is None or lon is None:
        return 0
    return sum(1 for plat, plon in points if _haversine_km(lat, lon, plat, plon) <= radius_km)


async def _live_history(
    db: AsyncSession,
    assets: list[InfrastructureAsset],
    settings: Settings,
) -> tuple[dict[uuid.UUID, dict], dict[uuid.UUID, float]]:
    """Per-asset {complaints_90d, repairs_12m} + ward resident counts."""
    now = datetime.now(UTC)
    radius_km = settings.INFRA_RADIUS_M / 1000.0

    complaint_points: list[tuple[float, float]] = []
    complaints_since = now - timedelta(days=settings.INFRA_COMPLAINTS_LOOKBACK_DAYS)
    complaint_rows = (
        await db.execute(
            select(ComplaintLocation.latitude, ComplaintLocation.longitude)
            .join(Complaint, Complaint.id == ComplaintLocation.complaint_id)
            .where(
                Complaint.created_at >= complaints_since,
                ComplaintLocation.latitude.is_not(None),
                ComplaintLocation.longitude.is_not(None),
            )
        )
    ).all()
    complaint_points = [(float(r[0]), float(r[1])) for r in complaint_rows]

    repair_points: list[tuple[float, float]] = []
    repairs_since = now - timedelta(days=settings.INFRA_REPAIRS_LOOKBACK_DAYS)
    repair_rows = (
        await db.execute(
            select(ComplaintLocation.latitude, ComplaintLocation.longitude)
            .join(Complaint, Complaint.id == ComplaintLocation.complaint_id)
            .join(WorkOrder, WorkOrder.complaint_id == Complaint.id)
            .where(
                WorkOrder.created_at >= repairs_since,
                ComplaintLocation.latitude.is_not(None),
                ComplaintLocation.longitude.is_not(None),
            )
        )
).all()
    repair_points = [(float(r[0]), float(r[1])) for r in repair_rows]

    counts: dict[uuid.UUID, dict] = {}
    for asset in assets:
        counts[asset.id] = {
            "complaints_90d": _count_near(
                asset.latitude, asset.longitude, complaint_points, radius_km
            ),
            "repairs_12m": _count_near(
                asset.latitude, asset.longitude, repair_points, radius_km
            ),
        }

    residents: dict[uuid.UUID, float] = {}
    res_rows = (
        await db.execute(
            select(Ward.id, func.count(User.id).label("residents"))
            .join(User, User.ward_id == Ward.id)
            .group_by(Ward.id)
        )
    ).all()
    residents = {str(wid): float(c) for wid, c in res_rows}
    return counts, residents


async def get_predictions(
    db: AsyncSession,
    user: User,
    settings: Settings | None = None,
) -> InfrastructurePredictions:
    settings = settings or get_settings()

    # Part 31 gate: forecasts require a real registered fleet. No lazy
    # provisioning — an empty asset registry must STAY empty of AI output.
    registered = await _asset_count(db)
    if registered < settings.INFRA_MIN_ASSETS:
        return InfrastructurePredictions(
            ai_prediction=True,
            disclaimer=_DISCLAIMER,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=None,
            assets=[],
            message=_infra_gate_message(registered, settings.INFRA_MIN_ASSETS),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
        )

    row = await db.scalar(
        select(InfrastructureModel).where(InfrastructureModel.is_active.is_(True))
    )
    if row is None:
        await train(db, user, settings)
        row = await db.scalar(
            select(InfrastructureModel).where(InfrastructureModel.is_active.is_(True))
        )
        if row is None:
            raise RuntimeError("Infrastructure training failed to produce an active model")

    bundle = await asyncio.to_thread(
        load_bundle, str(_artifact_path(settings, row.artifact_filename))
    )

    assets = (
        (
            await db.execute(
                select(InfrastructureAsset)
                .options(selectinload(InfrastructureAsset.ward))
                .where(InfrastructureAsset.is_active.is_(True))
                .order_by(InfrastructureAsset.name.asc())
            )
        )
        .scalars()
        .all()
    )

    counts, residents = await _live_history(db, assets, settings)
    rain_mm, rain_available = await fetch_infra_citywide_rainfall(settings)

    reference = datetime.now(UTC)
    feature_rows: list[dict] = []
    for asset in assets:
        installed = asset.installed_at
        history = counts.get(asset.id, {"complaints_90d": 0, "repairs_12m": 0})
        age = age_years(installed, reference)
        feature_rows.append(
            build_feature_dict(
                category=asset.category.value,
                age=age,
                complaints_90d=history["complaints_90d"],
                repairs_12m=history["repairs_12m"],
                rainfall_mm=rain_mm if rain_available else None,
                residents=residents.get(str(asset.ward_id)) if asset.ward_id else None,
                location_available=asset.latitude is not None and asset.longitude is not None,
            )
        )

    proba: list[float] = []
    if feature_rows:
        live_frame = pd.DataFrame(feature_rows, columns=feature_columns())
        predicted = await asyncio.to_thread(predict_from_bundle, bundle, live_frame)
        proba = [float(p) for p in predicted]

    predictions: list[AssetPrediction] = []
    for i, asset in enumerate(assets):
        prob = proba[i] if i < len(proba) else 0.0
        risk = risk_level_for_probability(prob, settings)
        recommended = recommendation_for(risk, asset.category.value)
        history = counts.get(asset.id, {"complaints_90d": 0, "repairs_12m": 0})
        age = age_years(asset.installed_at, reference)
        ward_label = None
        if asset.ward:
            ward_label = f"{asset.ward.code} ({asset.ward.name})"
        factors = supporting_factors_for(
            category=asset.category.value,
            age=age,
            age_available=asset.installed_at is not None,
            complaints_90d=history["complaints_90d"],
            repairs_12m=history["repairs_12m"],
            rainfall_mm=rain_mm if rain_available else None,
            ward_label=ward_label,
            location_available=asset.latitude is not None and asset.longitude is not None,
        )
        history_snapshot = {
            "complaints_90d": history["complaints_90d"],
            "repairs_12m": history["repairs_12m"],
            "age_years": round(age, 2),
            "radius_m": settings.INFRA_RADIUS_M,
            "rainfall_available": rain_available,
            "lookback_days": settings.INFRA_COMPLAINTS_LOOKBACK_DAYS,
        }

        stored = InfrastructurePrediction(
            asset_id=asset.id,
            model_version=row.version,
            failure_probability=round(prob, 4),
            risk_level=risk,
            recommended_inspection=recommended,
            supporting_factors=factors,
            history=history_snapshot,
            ai_prediction=True,
            review_status=PredictionReviewStatus.PENDING,
        )
        db.add(stored)
        await db.flush()
        predictions.append(
            AssetPrediction(
                id=str(stored.id),
                asset=_asset_out(asset),
                model_version=row.version,
                failure_probability=round(prob, 4),
                risk_level=risk.value,
                recommended_inspection=recommended,
                supporting_factors=factors,
                history=history_snapshot,
                ai_prediction=True,
                review_status=stored.review_status.value,
                predicted_at=stored.created_at,
            )
        )

    await db.commit()

    predictions.sort(key=lambda p: p.failure_probability, reverse=True)
    return InfrastructurePredictions(
        ai_prediction=True,
        disclaimer=_DISCLAIMER,
        prediction_status=PredictionStatus.READY,
        inference_at=reference,
        model=_model_info(row),
        assets=predictions,
        assets_assessed=len(predictions),
        assets_skipped=0,
        horizon_days=bundle["config"]["horizon_days"],
        message="Forecasts served from the trained infrastructure model.",
        registered_assets=registered,
        minimum_assets=settings.INFRA_MIN_ASSETS,
    )


# --------------------------------------------------------------------------- #
# Officer review + preventive work order
# --------------------------------------------------------------------------- #
async def review_prediction(
    db: AsyncSession,
    user: User,
    prediction_id: uuid.UUID,
    decision: str,
    note: str | None,
) -> InfrastructureReviewOut | None:
    if decision not in _EXPECTED_REVIEW_DECISIONS:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Review decision must be one of {sorted(_EXPECTED_REVIEW_DECISIONS)}",
        )
    stored = await db.get(InfrastructurePrediction, prediction_id)
    if stored is None:
        return None
    stored.review_status = PredictionReviewStatus(decision)
    stored.reviewed_by = user.id
    stored.reviewed_at = datetime.now(UTC)
    stored.review_note = note
    await db.commit()
    await db.refresh(stored)
    return InfrastructureReviewOut(
        id=str(stored.id),
        review_status=stored.review_status.value,
        reviewed_by=str(stored.reviewed_by) if stored.reviewed_by else None,
        reviewed_at=stored.reviewed_at,
        review_note=stored.review_note,
    )


async def create_preventive_work_order(
    db: AsyncSession,
    user: User,
    prediction_id: uuid.UUID,
    *,
    department: str,
    recommended_action: str | None,
    due_at: datetime | None,
    note: str | None,
    settings: Settings | None = None,
) -> PreventiveWorkOrderOut | None:
    settings = settings or get_settings()
    stored = (
        await db.scalar(
            select(InfrastructurePrediction)
            .options(selectinload(InfrastructurePrediction.asset).selectinload(InfrastructureAsset.ward))
            .where(InfrastructurePrediction.id == prediction_id)
        )
    )
    if stored is None:
        return None
    if stored.review_status != PredictionReviewStatus.APPROVED:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only an officer-APPROVED prediction may create a preventive work order.",
        )
    action = recommended_action or recommend_action_text(
        stored.risk_level, stored.asset.category.value
    )
    order = PreventiveWorkOrder(
        prediction_id=stored.id,
        asset_id=stored.asset_id,
        department=department,
        recommended_action=action,
        status=PreventiveWorkOrderStatus.PENDING_APPROVAL,
        due_at=due_at,
        created_by=user.id,
        note=note,
    )
    db.add(order)
    await db.commit()
    await db.refresh(order)
    order.asset = stored.asset
    return _preventive_out(order)


def _preventive_out(order: PreventiveWorkOrder) -> PreventiveWorkOrderOut:
    asset = order.asset
    return PreventiveWorkOrderOut(
        id=str(order.id),
        prediction_id=str(order.prediction_id),
        asset=_asset_out(asset),
        department=order.department,
        recommended_action=order.recommended_action,
        status=order.status.value,
        due_at=order.due_at,
        created_by=str(order.created_by) if order.created_by else None,
        approved_by=str(order.approved_by) if order.approved_by else None,
        approved_at=order.approved_at,
        note=order.note,
        created_at=order.created_at,
    )
