"""Predictive Infrastructure Maintenance service layer (Part 24).

Facades the infra ML pipeline behind async, DB-bound operations:

* ``train`` - builds the deterministic synthetic asset corpus, runs the
  time-aware training loop (offloaded to a thread), writes the joblib artifact
  and records it in the ``infrastructure_models`` registry (exactly one active).
* ``get_status`` - exposes the active infra model + its evaluation metrics.
* ``list_assets`` / ``register_asset`` - asset registry management.
* ``get_predictions`` - live inference: real asset records, nearby complaints,
  repair history, ward population and (optionally) rainfall feed the same
  feature extractor the model was trained on; risk = P(failure within the
  horizon). Every output is flagged ``ai_prediction`` and phrased as predicted
  risk / recommended inspection.
* ``review_prediction`` / ``create_preventive_work_order`` - the officer review
  workflow and the optional preventive work order raised on an approved asset.
"""

from __future__ import annotations

import asyncio
import math
import time
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pandas as pd
from fastapi import HTTPException, status
from sqlalchemy import func, select, text, update
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.config import Settings, get_settings
from app.ml.external import fetch_infra_citywide_rainfall
from app.ml.infra_features import (
    age_years,
    build_feature_dict,
    feature_columns,
    recommend_action_text,
    recommendation_for,
    risk_level_for_probability,
    supporting_factors_for,
)
from app.ml.infra_pipeline import (
    load_bundle,
    predict_from_bundle,
    run_infra_training,
    save_bundle,
)
from app.ml.readiness import PredictionStatus
from app.models import (
    Complaint,
    ComplaintLocation,
    CriticalLocation,
    InfrastructureAsset,
    InfrastructureModel,
    InfrastructurePrediction,
    PreventiveWorkOrder,
    User,
    Ward,
    WorkOrder,
)
from app.models.enums import (
    CriticalLocationCategory,
    InfrastructureCategory,
    InfrastructureDataStatus,
    PredictionReviewStatus,
    PreventiveWorkOrderStatus,
)
from app.schemas.infrastructure import (
    AssetPrediction,
    AssetRegistryCategoryCounts,
    AssetRegistrySyncOut,
    InfrastructureAssetIn,
    InfrastructureAssetOut,
    InfrastructureModelInfo,
    InfrastructurePredictions,
    InfrastructureReviewOut,
    InfrastructureStatus,
    InfrastructureTrainingOut,
    PreventiveWorkOrderOut,
)

_DISCLAIMER = (
    "AI-predicted maintenance risk for infrastructure assets, generated by the "
    "trained infrastructure model. This is a forecast, NOT a confirmed list of "
    "failing assets. Probabilities blend historical complaints, repair history, "
    "asset age, weather and location signals and may be wrong; verify any "
    "at-risk asset before dispatching."
)

_EXPECTED_REVIEW_DECISIONS = {
    PredictionReviewStatus.APPROVED.value,
    PredictionReviewStatus.REJECTED.value,
}

# --------------------------------------------------------------------------- #
# Real asset registry provenance + legitimate history linkage (Part 37)
# --------------------------------------------------------------------------- #
# Source markers carried onto every asset registered from the verified facility
# registry, mirroring the CriticalLocation provenance.
_ASSET_SOURCE = "openstreetmap"
_ASSET_SOURCE_DATASET = "OpenStreetMap (Overpass API, Pune, Maharashtra)"

# Only critical-location categories with a faithful maintainable asset kind are
# registered. Facility categories without an exact InfrastructureCategory match
# (hospitals, schools, police/fire stations, bus stops, transport) are left out
# deliberately: an asset is only created when the source data genuinely
# describes a maintainable municipal asset.
_REGISTRY_TO_ASSET: dict[CriticalLocationCategory, InfrastructureCategory] = {
    CriticalLocationCategory.ROAD: InfrastructureCategory.ROAD,
}

# Historical complaints only count toward an asset when their category genuinely
# relates to the asset kind (spatial proximity alone is not enough). Empty means
# the asset kind has no legitimate complaint category, so its history honestly
# stays at zero rather than inheriting unrelated signal.
_RELEVANT_COMPLAINT_CATEGORIES: dict[str, frozenset[str]] = {
    "ROAD": frozenset({"ROAD"}),
    "BRIDGE": frozenset({"ROAD"}),
    "WATER_MAIN": frozenset({"WATER", "WATER_LEAK"}),
    "SEWER": frozenset(),
    "DRAINAGE": frozenset({"DRAINAGE", "FLOODING"}),
    "STREET_LIGHTING": frozenset({"STREET_LIGHTING"}),
    "PARK": frozenset({"PARKS"}),
    "PUBLIC_BUILDING": frozenset(),
}


def _artifact_path(settings: Settings, filename: str) -> Path:
    return Path(settings.INFRA_ARTIFACT_DIR) / filename


# --------------------------------------------------------------------------- #
# Training / status
# --------------------------------------------------------------------------- #
async def _train_sync(settings: Settings) -> dict:
    return await asyncio.to_thread(run_infra_training, settings)


async def _next_version(db: AsyncSession) -> int:
    last = await db.scalar(select(func.max(InfrastructureModel.version)))
    return int(last) + 1 if last else 1


def _model_info(row: InfrastructureModel) -> InfrastructureModelInfo:
    return InfrastructureModelInfo(
        version=row.version,
        kind=row.kind,
        status=row.status,
        is_active=row.is_active,
        trained_at=row.trained_at,
        artifact_filename=row.artifact_filename,
        metrics=row.metrics or {},
        config=row.config or {},
    )


async def _asset_count(db: AsyncSession) -> int:
    return int(
        await db.scalar(
            select(func.count(InfrastructureAsset.id)).where(
                InfrastructureAsset.is_active.is_(True)
            )
        )
        or 0
    )


async def get_status(
    db: AsyncSession,
    settings: Settings | None = None,
) -> InfrastructureStatus:
    settings = settings or get_settings()
    registered = await _asset_count(db)
    row = await db.scalar(
        select(InfrastructureModel).where(InfrastructureModel.is_active.is_(True))
    )
    model_info = _model_info(row) if row is not None else None

    # Part 31 fleet gate: no registered fleet, no forecasts.
    if registered < settings.INFRA_MIN_ASSETS:
        return InfrastructureStatus(
            trained=row is not None,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=model_info,
            message=_infra_gate_message(registered, settings.INFRA_MIN_ASSETS),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
            history_records=0,
            minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
        )

    # Part 37 history gate: a real fleet is not enough on its own — forecasts
    # stay off until REAL maintenance history has accumulated for those assets.
    history_records, complaints, repairs = await _linked_history(db, settings)
    if history_records < settings.INFRA_MIN_HISTORY_RECORDS:
        return InfrastructureStatus(
            trained=row is not None,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=model_info,
            message=_infra_history_gate_message(
                history_records,
                complaints,
                repairs,
                settings.INFRA_MIN_HISTORY_RECORDS,
            ),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
            history_records=history_records,
            minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
        )

    if row is None:
        return InfrastructureStatus(
            trained=False,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=None,
            message=(
                "Enough real assets and maintenance history are registered, but no "
                "active infrastructure model exists yet. Retrain the model to enable "
                "forecasts."
            ),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
            history_records=history_records,
            minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
        )
    return InfrastructureStatus(
        trained=True,
        prediction_status=PredictionStatus.READY,
        model=model_info,
        message="Active predictive infrastructure model, forecasts are being served.",
        registered_assets=registered,
        minimum_assets=settings.INFRA_MIN_ASSETS,
        history_records=history_records,
        minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
    )


def _infra_gate_message(registered: int, minimum: int) -> str:
    return (
        "The infrastructure model is not ready yet: "
        f"{registered}/{minimum} registered assets are required. Register real "
        "assets in the asset registry before forecasts are enabled."
    )


def _infra_history_gate_message(
    history_records: int, complaints: int, repairs: int, minimum: int
) -> str:
    return (
        "Assets registered, but there is not enough maintenance history to train the "
        f"prediction model yet. {history_records}/{minimum} linked complaint/repair "
        f"records are required ({complaints} legitimate complaints, {repairs} repairs); "
        "only complaints and repairs that are close to a matching asset — spatially "
        "and by category — count."
    )


async def train(
    db: AsyncSession,
    user: User | None,
    settings: Settings | None = None,
) -> InfrastructureTrainingOut:
    settings = settings or get_settings()

    # Part 31 gate: refuse to train without a real, on-the-books fleet.
    registered = await _asset_count(db)
    if registered < settings.INFRA_MIN_ASSETS:
        return InfrastructureTrainingOut(
            trained=False,
            status=PredictionStatus.INSUFFICIENT_DATA,
            message=_infra_gate_message(registered, settings.INFRA_MIN_ASSETS),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
            history_records=0,
            minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
        )

    # Part 37 gate: training additionally requires enough REAL legitimately
    # linked maintenance history — a registered fleet alone is not a model.
    history_records, complaints, repairs = await _linked_history(db, settings)
    if history_records < settings.INFRA_MIN_HISTORY_RECORDS:
        return InfrastructureTrainingOut(
            trained=False,
            status=PredictionStatus.INSUFFICIENT_DATA,
            message=_infra_history_gate_message(
                history_records,
                complaints,
                repairs,
                settings.INFRA_MIN_HISTORY_RECORDS,
            ),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
            history_records=history_records,
            minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
        )

    started = time.monotonic()
    bundle = await _train_sync(settings)
    duration = round(time.monotonic() - started, 2)

    version = await _next_version(db)
    filename = f"infrastructure_v{version}.joblib"
    path = _artifact_path(settings, filename)
    path.parent.mkdir(parents=True, exist_ok=True)
    await asyncio.to_thread(save_bundle, bundle, str(path))

    await db.execute(
        update(InfrastructureModel)
        .where(InfrastructureModel.is_active.is_(True))
        .values(is_active=False)
    )
    row = InfrastructureModel(
        version=version,
        kind=bundle["kind"],
        artifact_filename=filename,
        metrics=bundle["metrics"],
        config=bundle["config"],
        status="ready",
        is_active=True,
        trained_by_user_id=user.id if user else None,
        trained_at=datetime.now(UTC),
    )
    db.add(row)
    await db.commit()
    await db.refresh(row)

    return InfrastructureTrainingOut(
        trained=True,
        status=PredictionStatus.READY,
        version=version,
        model=_model_info(row),
        metrics=bundle["metrics"],
        config=bundle["config"],
        rows=bundle["config"]["training_rows"],
        duration_seconds=duration,
        message="Infrastructure model trained on the configured asset corpus.",
        registered_assets=registered,
        minimum_assets=settings.INFRA_MIN_ASSETS,
        history_records=history_records,
        minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
    )


# --------------------------------------------------------------------------- #
# Asset registry
# --------------------------------------------------------------------------- #
def _asset_out(asset: InfrastructureAsset) -> InfrastructureAssetOut:
    ward = asset.ward
    return InfrastructureAssetOut(
        id=str(asset.id),
        name=asset.name,
        category=asset.category.value if hasattr(asset.category, "value") else str(asset.category),
        ward_id=str(asset.ward_id) if asset.ward_id else None,
        ward_code=ward.code if ward else None,
        ward_name=ward.name if ward else None,
        latitude=asset.latitude,
        longitude=asset.longitude,
        address=asset.address,
        installed_at=asset.installed_at,
        condition_note=asset.condition_note,
        is_active=asset.is_active,
        source=asset.source,
        source_dataset=asset.source_dataset,
        source_url=asset.source_url,
        source_id=asset.source_id,
        created_at=asset.created_at,
    )


async def list_assets(db: AsyncSession) -> list[InfrastructureAssetOut]:
    rows = (
        (
            await db.execute(
                select(InfrastructureAsset)
                .options(selectinload(InfrastructureAsset.ward))
                .where(InfrastructureAsset.is_active.is_(True))
                .order_by(InfrastructureAsset.created_at.asc())
            )
        )
        .scalars()
        .all()
    )
    return [_asset_out(a) for a in rows]


async def register_asset(
    db: AsyncSession, payload: InfrastructureAssetIn
) -> InfrastructureAssetOut:
    if payload.category not in InfrastructureCategory.__members__:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Unknown infrastructure category: {payload.category}",
        )
    asset = InfrastructureAsset(
        name=payload.name,
        category=InfrastructureCategory(payload.category),
        ward_id=uuid.UUID(payload.ward_id) if payload.ward_id else None,
        latitude=payload.latitude,
        longitude=payload.longitude,
        address=payload.address,
        installed_at=payload.installed_at,
        condition_note=payload.condition_note,
        is_active=True,
    )
    db.add(asset)
    await db.commit()
    await db.refresh(asset)
    # Resolve the ward eagerly so the response schema never lazy-loads.
    if asset.ward_id:
        asset.ward = await db.get(Ward, asset.ward_id)
    return _asset_out(asset)


async def _resolve_asset_wards(
    db: AsyncSession,
    records: list[CriticalLocation],
) -> dict[str, uuid.UUID | None]:
    """Map registry record id -> ward via PostGIS point-in-polygon (bulk).

    Ward assignment is geographic containment against the real ward-boundary
    polygons — never a nearest-centroid guess — and the source coordinates are
    never rewritten.
    """
    if not records:
        return {}
    points = [
        (str(r.id), float(r.latitude), float(r.longitude))
        for r in records
        if r.latitude is not None and r.longitude is not None
    ]
    if not points:
        return {}
    entries = ", ".join(
        f"('{key}', ST_SetSRID(ST_MakePoint({lon!r}, {lat!r}), 4326))"
        for key, lat, lon in points
    )
    sql = (
        "SELECT p.k AS k, wb.ward_id AS ward_id FROM "
        f"(VALUES {entries}) AS p(k, geom) "
        "JOIN ward_boundaries wb ON ST_Contains(wb.geom, p.geom)"
    )
    rows = (await db.execute(text(sql))).all()
    result: dict[str, uuid.UUID | None] = {key: None for key, *_ in points}
    for row in rows:
        result[row.k] = row.ward_id
    return result


async def sync_assets_from_registry(
    db: AsyncSession,
    settings: Settings | None = None,
) -> AssetRegistrySyncOut:
    """Register REAL maintainable assets from the verified facility registry.

    Reads the facility registry (``critical_locations``) records that map to a
    maintainable asset kind (currently ROAD), assigns wards by PostGIS
    point-in-polygon and upserts assets keyed on ``(source, source_id)`` — so it
    is idempotent and never fabricates an asset, coordinate or install date.
    """
    settings = settings or get_settings()

    rows = (
        (
            await db.execute(
                select(CriticalLocation)
                .where(
                    CriticalLocation.verification_status
                    == InfrastructureDataStatus.FOUND,
                    CriticalLocation.is_active.is_(True),
                    CriticalLocation.category.in_(
                        list(_REGISTRY_TO_ASSET.keys())
                    ),
                    CriticalLocation.latitude.is_not(None),
                    CriticalLocation.longitude.is_not(None),
                )
            )
        )
        .scalars()
        .all()
    )

    # Intra-run dedup on (source_id, coords) — never register the same real
    # record twice; the DIFFERENT source_id across re-syncs is handled below.
    seen: set[tuple[str, str]] = set()
    candidates: list[CriticalLocation] = []
    unlocated = 0
    for row in rows:
        if not row.source or not row.source_id:
            unlocated += 1
            continue
        key = (row.source_id, f"{row.latitude:.6f},{row.longitude:.6f}")
        if key in seen:
            continue
        seen.add(key)
        candidates.append(row)

    ward_map = await _resolve_asset_wards(db, candidates)

    existing_rows = (
        (
            await db.execute(
                select(InfrastructureAsset).where(
                    InfrastructureAsset.source.is_not(None),
                    InfrastructureAsset.source_id.is_not(None),
                )
            )
        )
        .scalars()
        .all()
    )
    # Keyed on the record's OWN (source, source_id) so each registry record maps
    # to exactly one asset regardless of where the record came from — re-running
    # a sync over the current fleet updates or skips instead of re-inserting.
    existing = {(row.source, row.source_id): row for row in existing_rows}

    by_category: dict[str, AssetRegistryCategoryCounts] = {}
    inserted = updated = skipped = 0

    for record in candidates:
        category = _REGISTRY_TO_ASSET[record.category]
        counts = by_category.setdefault(
            category.value,
            AssetRegistryCategoryCounts(
                category=record.category.value, asset_category=category.value
            ),
        )
        counts.available += 1
        ward_id = ward_map.get(str(record.id)) or None
        key = (record.source, record.source_id)
        asset = existing.get(key)
        if asset is not None:
            changed = (
                asset.name != record.name
                or asset.latitude != record.latitude
                or asset.longitude != record.longitude
                or asset.address != record.address
                or asset.ward_id != ward_id
                or not asset.is_active
            )
            asset.name = record.name
            asset.latitude = record.latitude
            asset.longitude = record.longitude
            asset.address = record.address
            asset.ward_id = ward_id
            asset.is_active = True
            if changed:
                counts.updated += 1
                updated += 1
            else:
                counts.skipped_duplicate += 1
                skipped += 1
            continue
        counts.registered += 1
        inserted += 1
        db.add(
            InfrastructureAsset(
                name=record.name,
                category=category,
                ward_id=ward_id,
                latitude=record.latitude,
                longitude=record.longitude,
                address=record.address,
                installed_at=None,
                condition_note=None,
                is_active=True,
                source=record.source,
                source_dataset=record.source_dataset or _ASSET_SOURCE_DATASET,
                source_url=record.source_url,
                source_id=record.source_id,
            )
        )

    await db.commit()
    registered_total = await _asset_count(db)
    message = (
        f"Registered {inserted} new + updated {updated} real assets from the verified "
        f"facility registry (skipped {skipped} unchanged, {unlocated} unlocated). "
        f"Total registered assets: {registered_total}. Source: {_ASSET_SOURCE_DATASET}. "
        "Installation dates are not present in the source data and were left unset."
    )
    return AssetRegistrySyncOut(
        source=_ASSET_SOURCE,
        source_dataset=_ASSET_SOURCE_DATASET,
        inserted=inserted,
        updated=updated,
        skipped_duplicate=skipped,
        unlocated=unlocated,
        registered_total=registered_total,
        by_category=list(by_category.values()),
        message=message,
    )


# --------------------------------------------------------------------------- #
# Live inference
# --------------------------------------------------------------------------- #
def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371.0088
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def _history_rows_for_asset(
    asset: InfrastructureAsset,
    radius_km: float,
    complaints: list[tuple[uuid.UUID, str, float, float]],
    repairs: list[tuple[uuid.UUID, str, float, float]],
) -> tuple[list[tuple[uuid.UUID, str, float, float]], list[tuple[uuid.UUID, str, float, float]]]:
    """Only history that is both spatially near AND categorically relevant."""
    relevant = _RELEVANT_COMPLAINT_CATEGORIES.get(asset.category.value, frozenset())
    if asset.latitude is None or asset.longitude is None:
        return [], []
    near_c = [
        r
        for r in complaints
        if r[1] in relevant
        and _haversine_km(asset.latitude, asset.longitude, r[2], r[3]) <= radius_km
    ]
    near_r = [
        r
        for r in repairs
        if r[1] in relevant
        and _haversine_km(asset.latitude, asset.longitude, r[2], r[3]) <= radius_km
    ]
    return near_c, near_r


async def _history_signals(
    db: AsyncSession,
    assets: list[InfrastructureAsset],
    settings: Settings,
) -> tuple[dict[uuid.UUID, dict], set[uuid.UUID], set[uuid.UUID]]:
    """Per-asset {complaints_90d, repairs_12m} + globally linked record ids.

    A record only counts when it is close to the asset (``INFRA_RADIUS_M``) AND
    its complaint category genuinely relates to the asset kind — so unrelated
    complaints never inflate an asset's history (or the readiness gate).
    """
    now = datetime.now(UTC)
    radius_km = settings.INFRA_RADIUS_M / 1000.0

    complaints: list[tuple[uuid.UUID, str, float, float]] = []
    complaints_since = now - timedelta(days=settings.INFRA_COMPLAINTS_LOOKBACK_DAYS)
    c_rows = (
        await db.execute(
            select(
                Complaint.id,
                Complaint.category,
                ComplaintLocation.latitude,
                ComplaintLocation.longitude,
            )
            .join(ComplaintLocation, ComplaintLocation.complaint_id == Complaint.id)
            .where(
                Complaint.created_at >= complaints_since,
                ComplaintLocation.latitude.is_not(None),
                ComplaintLocation.longitude.is_not(None),
            )
        )
    ).all()
    for row in c_rows:
        cat = row.category.value if hasattr(row.category, "value") else str(row.category)
        complaints.append((row.id, cat, float(row.latitude), float(row.longitude)))

    repairs: list[tuple[uuid.UUID, str, float, float]] = []
    repairs_since = now - timedelta(days=settings.INFRA_REPAIRS_LOOKBACK_DAYS)
    r_rows = (
        await db.execute(
            select(
                Complaint.id,
                Complaint.category,
                ComplaintLocation.latitude,
                ComplaintLocation.longitude,
            )
            .join(ComplaintLocation, ComplaintLocation.complaint_id == Complaint.id)
            .join(WorkOrder, WorkOrder.complaint_id == Complaint.id)
            .where(
                WorkOrder.created_at >= repairs_since,
                ComplaintLocation.latitude.is_not(None),
                ComplaintLocation.longitude.is_not(None),
            )
        )
    ).all()
    for row in r_rows:
        cat = row.category.value if hasattr(row.category, "value") else str(row.category)
        repairs.append((row.id, cat, float(row.latitude), float(row.longitude)))

    counts: dict[uuid.UUID, dict] = {}
    linked_complaints: set[uuid.UUID] = set()
    linked_repairs: set[uuid.UUID] = set()
    for asset in assets:
        near_c, near_r = _history_rows_for_asset(asset, radius_km, complaints, repairs)
        counts[asset.id] = {
            "complaints_90d": len(near_c),
            "repairs_12m": len(near_r),
        }
        linked_complaints.update(r[0] for r in near_c)
        linked_repairs.update(r[0] for r in near_r)

    return counts, linked_complaints, linked_repairs


async def _ward_residents(db: AsyncSession) -> dict[str, float]:
    """Ward id -> number of registered social users (population-density proxy)."""
    res_rows = (
        await db.execute(
            select(Ward.id, func.count(User.id).label("residents"))
            .join(User, User.ward_id == Ward.id)
            .group_by(Ward.id)
        )
    ).all()
    return {str(wid): float(c) for wid, c in res_rows}


async def _linked_history(
    db: AsyncSession,
    settings: Settings,
) -> tuple[int, int, int]:
    """``(records, complaints, repairs)`` of real history linked to any asset."""
    assets = (
        (
            await db.execute(
                select(InfrastructureAsset).where(InfrastructureAsset.is_active.is_(True))
            )
        )
        .scalars()
        .all()
    )
    _counts, linked_complaints, linked_repairs = await _history_signals(db, assets, settings)
    return (
        len(linked_complaints | linked_repairs),
        len(linked_complaints),
        len(linked_repairs),
    )


async def get_predictions(
    db: AsyncSession,
    user: User,
    settings: Settings | None = None,
) -> InfrastructurePredictions:
    settings = settings or get_settings()

    # Part 31 gate: forecasts require a real registered fleet. No lazy
    # provisioning — an empty asset registry must STAY empty of AI output.
    registered = await _asset_count(db)
    if registered < settings.INFRA_MIN_ASSETS:
        return InfrastructurePredictions(
            ai_prediction=True,
            disclaimer=_DISCLAIMER,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=None,
            assets=[],
            message=_infra_gate_message(registered, settings.INFRA_MIN_ASSETS),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
            history_records=0,
            minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
        )

    # Part 37 gate: real maintenance history must exist for the fleet — a
    # registered fleet alone is not a prediction.
    history_records, complaints, repairs = await _linked_history(db, settings)
    if history_records < settings.INFRA_MIN_HISTORY_RECORDS:
        return InfrastructurePredictions(
            ai_prediction=True,
            disclaimer=_DISCLAIMER,
            prediction_status=PredictionStatus.INSUFFICIENT_DATA,
            model=None,
            assets=[],
            message=_infra_history_gate_message(
                history_records,
                complaints,
                repairs,
                settings.INFRA_MIN_HISTORY_RECORDS,
            ),
            registered_assets=registered,
            minimum_assets=settings.INFRA_MIN_ASSETS,
            history_records=history_records,
            minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
        )

    row = await db.scalar(
        select(InfrastructureModel).where(InfrastructureModel.is_active.is_(True))
    )
    if row is None:
        await train(db, user, settings)
        row = await db.scalar(
            select(InfrastructureModel).where(InfrastructureModel.is_active.is_(True))
        )
        if row is None:
            raise RuntimeError("Infrastructure training failed to produce an active model")

    bundle = await asyncio.to_thread(
        load_bundle, str(_artifact_path(settings, row.artifact_filename))
    )

    assets = (
        (
            await db.execute(
                select(InfrastructureAsset)
                .options(selectinload(InfrastructureAsset.ward))
                .where(InfrastructureAsset.is_active.is_(True))
                .order_by(InfrastructureAsset.name.asc())
            )
        )
        .scalars()
        .all()
    )

    counts, linked_complaints, linked_repairs = await _history_signals(db, assets, settings)
    residents = await _ward_residents(db)
    rain_mm, rain_available = await fetch_infra_citywide_rainfall(settings)

    reference = datetime.now(UTC)
    feature_rows: list[dict] = []
    for asset in assets:
        installed = asset.installed_at
        history = counts.get(asset.id, {"complaints_90d": 0, "repairs_12m": 0})
        age = age_years(installed, reference)
        feature_rows.append(
            build_feature_dict(
                category=asset.category.value,
                age=age,
                complaints_90d=history["complaints_90d"],
                repairs_12m=history["repairs_12m"],
                rainfall_mm=rain_mm if rain_available else None,
                residents=residents.get(str(asset.ward_id)) if asset.ward_id else None,
                location_available=asset.latitude is not None and asset.longitude is not None,
            )
        )

    proba: list[float] = []
    if feature_rows:
        live_frame = pd.DataFrame(feature_rows, columns=feature_columns())
        predicted = await asyncio.to_thread(predict_from_bundle, bundle, live_frame)
        proba = [float(p) for p in predicted]

    predictions: list[AssetPrediction] = []
    for i, asset in enumerate(assets):
        prob = proba[i] if i < len(proba) else 0.0
        risk = risk_level_for_probability(prob, settings)
        recommended = recommendation_for(risk, asset.category.value)
        history = counts.get(asset.id, {"complaints_90d": 0, "repairs_12m": 0})
        age = age_years(asset.installed_at, reference)
        ward_label = None
        if asset.ward:
            ward_label = f"{asset.ward.code} ({asset.ward.name})"
        factors = supporting_factors_for(
            category=asset.category.value,
            age=age,
            age_available=asset.installed_at is not None,
            complaints_90d=history["complaints_90d"],
            repairs_12m=history["repairs_12m"],
            rainfall_mm=rain_mm if rain_available else None,
            ward_label=ward_label,
            location_available=asset.latitude is not None and asset.longitude is not None,
        )
        history_snapshot = {
            "complaints_90d": history["complaints_90d"],
            "repairs_12m": history["repairs_12m"],
            "age_years": round(age, 2),
            "radius_m": settings.INFRA_RADIUS_M,
            "rainfall_available": rain_available,
            "lookback_days": settings.INFRA_COMPLAINTS_LOOKBACK_DAYS,
        }

        stored = InfrastructurePrediction(
            asset_id=asset.id,
            model_version=row.version,
            failure_probability=round(prob, 4),
            risk_level=risk,
            recommended_inspection=recommended,
            supporting_factors=factors,
            history=history_snapshot,
            ai_prediction=True,
            review_status=PredictionReviewStatus.PENDING,
        )
        db.add(stored)
        await db.flush()
        predictions.append(
            AssetPrediction(
                id=str(stored.id),
                asset=_asset_out(asset),
                model_version=row.version,
                failure_probability=round(prob, 4),
                risk_level=risk.value,
                recommended_inspection=recommended,
                supporting_factors=factors,
                history=history_snapshot,
                ai_prediction=True,
                review_status=stored.review_status.value,
                predicted_at=stored.created_at,
            )
        )

    await db.commit()

    predictions.sort(key=lambda p: p.failure_probability, reverse=True)
    return InfrastructurePredictions(
        ai_prediction=True,
        disclaimer=_DISCLAIMER,
        prediction_status=PredictionStatus.READY,
        inference_at=reference,
        model=_model_info(row),
        assets=predictions,
        assets_assessed=len(predictions),
        assets_skipped=0,
        horizon_days=bundle["config"]["horizon_days"],
        message="Forecasts served from the trained infrastructure model.",
        registered_assets=registered,
        minimum_assets=settings.INFRA_MIN_ASSETS,
        history_records=history_records,
        minimum_history=settings.INFRA_MIN_HISTORY_RECORDS,
    )


# --------------------------------------------------------------------------- #
# Officer review + preventive work order
# --------------------------------------------------------------------------- #
async def review_prediction(
    db: AsyncSession,
    user: User,
    prediction_id: uuid.UUID,
    decision: str,
    note: str | None,
) -> InfrastructureReviewOut | None:
    if decision not in _EXPECTED_REVIEW_DECISIONS:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Review decision must be one of {sorted(_EXPECTED_REVIEW_DECISIONS)}",
        )
    stored = await db.get(InfrastructurePrediction, prediction_id)
    if stored is None:
        return None
    stored.review_status = PredictionReviewStatus(decision)
    stored.reviewed_by = user.id
    stored.reviewed_at = datetime.now(UTC)
    stored.review_note = note
    await db.commit()
    await db.refresh(stored)
    return InfrastructureReviewOut(
        id=str(stored.id),
        review_status=stored.review_status.value,
        reviewed_by=str(stored.reviewed_by) if stored.reviewed_by else None,
        reviewed_at=stored.reviewed_at,
        review_note=stored.review_note,
    )


async def create_preventive_work_order(
    db: AsyncSession,
    user: User,
    prediction_id: uuid.UUID,
    *,
    department: str,
    recommended_action: str | None,
    due_at: datetime | None,
    note: str | None,
    settings: Settings | None = None,
) -> PreventiveWorkOrderOut | None:
    settings = settings or get_settings()
    stored = await db.scalar(
        select(InfrastructurePrediction)
        .options(
            selectinload(InfrastructurePrediction.asset).selectinload(InfrastructureAsset.ward)
        )
        .where(InfrastructurePrediction.id == prediction_id)
    )
    if stored is None:
        return None
    if stored.review_status != PredictionReviewStatus.APPROVED:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only an officer-APPROVED prediction may create a preventive work order.",
        )
    action = recommended_action or recommend_action_text(
        stored.risk_level, stored.asset.category.value
    )
    order = PreventiveWorkOrder(
        prediction_id=stored.id,
        asset_id=stored.asset_id,
        department=department,
        recommended_action=action,
        status=PreventiveWorkOrderStatus.PENDING_APPROVAL,
        due_at=due_at,
        created_by=user.id,
        note=note,
    )
    db.add(order)
    await db.commit()
    await db.refresh(order)
    order.asset = stored.asset
    return _preventive_out(order)


def _preventive_out(order: PreventiveWorkOrder) -> PreventiveWorkOrderOut:
    asset = order.asset
    return PreventiveWorkOrderOut(
        id=str(order.id),
        prediction_id=str(order.prediction_id),
        asset=_asset_out(asset),
        department=order.department,
        recommended_action=order.recommended_action,
        status=order.status.value,
        due_at=order.due_at,
        created_by=str(order.created_by) if order.created_by else None,
        approved_by=str(order.approved_by) if order.approved_by else None,
        approved_at=order.approved_at,
        note=order.note,
        created_at=order.created_at,
    )
