"""complaints model and user ward link

Revision ID: 621f36f8c889
Revises: 39e215098544
Create Date: 2026-09-02 18:45:37.764440
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "621f36f8c889"
down_revision: str | None = "39e215098544"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaints",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ward_id", sa.UUID(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "ROAD",
                "SANITATION",
                "WATER",
                "ELECTRICITY",
                "PUBLIC_SAFETY",
                "PARKS",
                "STREET_LIGHTING",
                "OTHER",
                name="complaint_category",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="complaint_priority"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "IN_PROGRESS", "RESOLVED", "ESCALATED", name="complaint_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ward_id"], ["wards.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_complaints_category"), "complaints", ["category"], unique=False)
    op.create_index(op.f("ix_complaints_priority"), "complaints", ["priority"], unique=False)
    op.create_index(op.f("ix_complaints_status"), "complaints", ["status"], unique=False)
    op.create_index(op.f("ix_complaints_user_id"), "complaints", ["user_id"], unique=False)
    op.create_index(op.f("ix_complaints_ward_id"), "complaints", ["ward_id"], unique=False)
    # NOTE: 'spatial_ref_sys' is a PostGIS system table — it is intentionally NOT in
    # Python metadata and must never be dropped by Autogenerate.
    op.add_column("users", sa.Column("ward_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_users_ward_id"), "users", ["ward_id"], unique=False)
    op.create_foreign_key(
        "fk_users_ward_id", "users", "wards", ["ward_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_ward_id", "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_ward_id"), table_name="users")
    op.drop_column("users", "ward_id")
    op.drop_index(op.f("ix_complaints_ward_id"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_user_id"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_status"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_priority"), table_name="complaints")
    op.drop_index(op.f("ix_complaints_category"), table_name="complaints")
    op.drop_table("complaints")
    # ### end Alembic commands ###
