"use client";

// Offline-first sync queue for the field worker app.
//
// Every workflow action runs through this queue: when the device is online the
// action is sent immediately; when offline it is persisted in localStorage and
// flushed in order after a reconnect. Each action carries a stable `client_ref`
// generated by the client, so a replayed action is idempotent on the server —
// the same action is never applied twice.
//
// Scope note: this is a queue-and-sync implementation. Files (before/after
// photos) are snapshotted as base64 data URLs and capped in size so they fit in
// localStorage. We deliberately do NOT claim full offline/PWA support (no
// service worker, no offline asset caching).

import {
  acceptJob,
  checkIn,
  completeJob,
  saveWorkerNotes,
  startJob,
  uploadWorkOrderPhoto,
  type WorkerActionPayload,
} from "@/lib/field-worker-api";
import { ApiError } from "@/lib/auth-api";

const QUEUE_KEY = "ca_worker_queue_v1";
const MAX_OFFLINE_PHOTO_BYTES = 1.5 * 1024 * 1024;

export type QueuedActionKind =
  | "accept"
  | "check-in"
  | "start"
  | "notes"
  | "photo"
  | "complete";

export interface QueuedAction {
  id: string;
  orderId: string;
  kind: QueuedActionKind;
  activityType?: "EN_ROUTE" | "ARRIVED";
  note?: string | null;
  category?: "BEFORE" | "AFTER";
  fileDataUrl?: string;
  fileName?: string;
  fileType?: string;
  payload: WorkerActionPayload;
  queuedAt: string;
}

function readQueue(): QueuedAction[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(QUEUE_KEY);
    return raw ? (JSON.parse(raw) as QueuedAction[]) : [];
  } catch {
    return [];
  }
}

function writeQueue(items: QueuedAction[]) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(QUEUE_KEY, JSON.stringify(items));
  } catch {
    // localStorage full — drop oldest photo entry so the queue stays usable.
    try {
      const withoutPhoto = items.filter((i) => i.kind !== "photo");
      localStorage.setItem(QUEUE_KEY, JSON.stringify(withoutPhoto));
    } catch {
      // ignore
    }
  }
}

export function newClientRef(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return `ref-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export interface QueueEnqueueResult {
  ok: boolean;
  offline: boolean;
  message?: string;
}

export function enqueueAction(
  action: Omit<QueuedAction, "id" | "queuedAt">
): QueueEnqueueResult {
  if (action.kind === "photo") {
    if (!action.fileDataUrl) return { ok: false, offline: !isOnline(), message: "No photo attached." };
    const approxBytes = Math.ceil((action.fileDataUrl.length * 3) / 4);
    if (approxBytes > MAX_OFFLINE_PHOTO_BYTES) {
      return {
        ok: false,
        offline: !isOnline(),
        message:
          "This photo is too large to queue offline. Retry once the device is back online.",
      };
    }
  }
  const offline = !isOnline();
  const items = readQueue();
  items.push({ ...action, id: newClientRef(), queuedAt: new Date().toISOString() });
  writeQueue(items);
  return { ok: true, offline };
}

export function pendingCount(): number {
  return readQueue().length;
}

export function isOnline(): boolean {
  if (typeof navigator === "undefined") return true;
  return navigator.onLine !== false;
}

export interface SyncReport {
  synced: number;
  remaining: number;
  error?: string;
}

async function syncOne(action: QueuedAction): Promise<void> {
  switch (action.kind) {
    case "accept":
      await acceptJob(action.orderId, action.payload);
      return;
    case "check-in":
      await checkIn(
        action.orderId,
        action.activityType || "EN_ROUTE",
        action.payload
      );
      return;
    case "start":
      await startJob(action.orderId, action.payload);
      return;
    case "notes":
      await saveWorkerNotes(action.orderId, action.note ?? "", action.payload.client_ref);
      return;
    case "photo": {
      if (!action.fileDataUrl || !action.fileType) {
        throw new ApiError(400, "Queued photo payload is missing its data.");
      }
      const blob = dataUrlToBlob(action.fileDataUrl, action.fileType);
      const file = new File(
        [blob],
        action.fileName || `${action.category?.toLowerCase() || "photo"}.jpg`,
        { type: action.fileType }
      );
      await uploadWorkOrderPhoto(action.orderId, file, action.category || "BEFORE", {
        client_ref: action.payload.client_ref,
        latitude: action.payload.latitude,
        longitude: action.payload.longitude,
        geo_denied: action.payload.geo_denied,
      });
      return;
    }
    case "complete":
      await completeJob(action.orderId, action.payload);
      return;
  }
}

export function dataUrlToBlob(dataUrl: string, mime: string): Blob {
  const index = dataUrl.indexOf(",");
  const raw = index >= 0 ? dataUrl.slice(index + 1) : dataUrl;
  const binary = atob(raw);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) {
    bytes[i] = binary.charCodeAt(i);
  }
  return new Blob([bytes], { type: mime });
}

// Resolves `undefined` when the queue is empty / all synced.
export async function processQueue(): Promise<SyncReport> {
  if (!isOnline()) return { synced: 0, remaining: pendingCount() };
  const items = readQueue();
  if (items.length === 0) return { synced: 0, remaining: 0 };

  let synced = 0;
  const retained: QueuedAction[] = [];
  for (const item of items) {
    try {
      await syncOne(item);
      synced += 1;
    } catch (err) {
      const status = err instanceof ApiError ? err.status : null;
      if (status === 401) {
        // Session lost — stop pushing; the UI will re-auth and retry.
        retained.push(item);
        writeQueue(retained.concat(items.slice(items.indexOf(item) + 1)));
        return { synced, remaining: retained.length + (items.length - items.indexOf(item) - 1), error: "Session expired." };
      }
      if (status && status < 500) {
        // A permanent client error — drop the poison action so it can't block
        // the rest of the queue forever (e.g. an unsupported photo).
        continue;
      }
      // Network/server hiccup: keep the item, stop for now.
      retained.push(item);
      writeQueue(retained.concat(items.slice(items.indexOf(item) + 1)));
      return {
        synced,
        remaining: retained.length + (items.length - items.indexOf(item) - 1),
        error: err instanceof Error ? err.message : "Sync failed.",
      };
    }
  }
  writeQueue(retained);
  return { synced, remaining: 0 };
}

export function onQueueChanged(listener: (count: number) => void): () => void {
  const notify = () => listener(pendingCount());
  const handle = () => notify();
  window.addEventListener("storage", handle);
  window.addEventListener("online", handle);
  window.addEventListener("offline", handle);
  return () => {
    window.removeEventListener("storage", handle);
    window.removeEventListener("online", handle);
    window.removeEventListener("offline", handle);
  };
}